const ProductData = [
    {
      image: "/product-thumb-1.png",
      type: "Tênis",
      name: "K-Swiss V8 - Masculino",
      price: 200,
      priceDiscount: 50,
      hasDiscount: true,
    },
    {
      image: "/product-thumb-1.png",
      type: "Tênis",
      name: "K-Swiss V8 - Masculino",
      price: 200,
      priceDiscount: 50,
      hasDiscount:false,
    },
    {
      image: "/product-thumb-1.png",
      type: "Tênis",
      name: "K-Swiss V8 - Masculino",
      price: 200,
      priceDiscount: 50,
      hasDiscount:false,
    },
    {
      image: "/product-thumb-1.png",
      type: "Tênis",
      name: "K-Swiss V8 - Masculino",
      price: 200,
      priceDiscount: 50,
      hasDiscount:false,
    },
    {
      image: "/product-thumb-1.png",
      type: "Tênis",
      name: "K-Swiss V8 - Masculino",
      price: 200,
      priceDiscount: 50, 
      hasDiscount:false,
    },
    {
      image: "/product-thumb-1.png",
      type: "Tênis",
      name: "K-Swiss V8 - Masculino",
      price: 200,
      priceDiscount: 50,
      hasDiscount:false, 
    },
    {
      image: "/product-thumb-1.png",
      type: "Tênis",
      name: "K-Swiss V8 - Masculino",
      price: 200,
      priceDiscount: 50,
      hasDiscount:false, 
    },
    {
      image: "/product-thumb-1.png",
      type: "Tênis",
      name: "K-Swiss V8 - Masculino",
      price: 149.9,
      priceDiscount: 50,
      hasDiscount:false, 
    },
  ];
  
  export default ProductData;